### ISSUE TITLE
Resources directory and some files missing. 

### ISSUE THREAD

**Issue by prestancedesign** [deckeraa/pouchdb-fx-examples#1]
Hi,

After the first launch, Shadow-CLJS output missing index.html error.
Some directories seems to be missing in this repo.

I had to manually create the index file to call `js/compiled/app.js`.

Best regards.

**Comment by deckeraa** [comment]
Yep, I had failed to commit index.html to git. Fixed in fd5c4b11ffb7d6c5d01e2640fc05c5b08456bd78.
